### ISSUE TITLE
主页怎样改成反代服务器？

### ISSUE THREAD

**Issue by gmdig** [totravel/shadowsocks-ws#11]
如题。想把index.html 改成例如127.0.0.1:5212，请问如何修改代码？谢谢

**Comment by totravel** [comment]
What do you mean?

**Comment by gmdig** [comment]
I have Cloudreve server running on port 5212 and deployed your project manually using "npm run dev". How to replace the default index.html (showing "You are free as a bird") with cloudreve?
I think server.mjs should be  modified to  create a reverse proxy for cloudreve server, but don't how.

**Comment by totravel** [comment]
shadowsocks-ws now support HTTP reverse proxy. You can specify the target host by setting the `PROXY` environment variable:

```bash
export PROXY='https://github.com'
npm run dev
```

**Comment by gmdig** [comment]
Thanks a lot!
