### ISSUE TITLE
mac 下 clashx 无法连接，端口都不通

### ISSUE THREAD

**Issue by kilvn** [totravel/shadowsocks-ws#12]
- railway的PORT是7890
- 打开主页显示 `You're free as a bird!`
- telnet x.up.railway.app 7890，端口无法连接`telnet: Unable to connect to remote host`
- 所以clashx也连不上

**Comment by totravel** [comment]
部署在 PaaS 时用环境变量 `PORT` 指定的端口是由平台在内部使用的，它最终会映射成 443 端口。所有常规 ss 客户端都不能直接连接 ss-ws 服务器。建议认真阅读说明文档和常见问题。

**Comment by totravel** [comment]
请阅读本项目的说明文档和常见问题。

**Comment by totravel** [comment]
Please describe your problem in detail, and synchronously post the error message, key log/code snippet, and reproduction steps. To enable development mode, you can set `NODE_ENV` to `development` before running `npm run` commands.
