### ISSUE TITLE
我只是想用来做反向代理，怎么做？

### ISSUE THREAD

**Issue by woshichenghaibo** [totravel/shadowsocks-ws#14]
就很简单的用，google来伪装成新部署的应用

**Comment by totravel** [comment]
设置环境变量 `PROXY='https://www.google.com'`。

需要注意的是，反向代理没有访问控制，这意味着一方面服务器有可能被滥用；另一方面代理黑名单上的网站有可能导致服务器也跟着被拉入黑名单。

反向代理的应用场景主要是用来代理私有云服务，如个人网盘服务 [Cloudreve](https://cloudreve.org/)。
