### ISSUE TITLE
browser and local server must be running on the same device?

### ISSUE THREAD

**Issue by opsforce** [totravel/shadowsocks-ws#2]
![image](https://user-images.githubusercontent.com/14209620/129340301-525f6e05-6cac-417d-a4d7-df0994a84dcc.png)

- test failed

  - 1 device(ios brower -> shadowrocket) -> other device(local server)

- test success

  - 1 device(macOS safari -> shadowsocks -> local server)

  - 1 device(macOS safari -> shadowsocks) -> other device(local server)

**Comment by totravel** [comment]
No, It needn't. In theory, just make sure the `local_address` is correct if local server is running on another device.

Actually, I haven't tested it on mobile phone yet. Could you provide more information?

**Comment by opsforce** [comment]
I finally confirmed: a bug of software on iphone cause proxy failure. 
thanks for your help
