### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by opsforce** [totravel/shadowsocks-ws#3]
Hi,

![image](https://user-images.githubusercontent.com/14209620/138207295-5d214f4d-8b68-48c6-a498-6a9da57652b7.png)

早上开始发现的，应该是夜里开始的，用了好几个月好好的，不知道出来什么问题。
我自己尝试了一些途径，依旧无法连接：
- 重启 heroku app
- 更换 本地 config.json 里的 dns, port
- 新建了 heroku app

**Comment by totravel** [comment]
经测试，目前代码尚可正常工作。出现图中无一 IP 地址可用的情况，首先考虑平台自身原因。建议：

- 升级代码到最新版本（务必）
- 修改 `dns` 字段为 `https://doh.pub/dns-query`

或者，先用浏览器（启用基于 HTTPS/SSH 的 DNS）访问服务器（地址为 `http://<your-app>.herokuapp.com`）。若能访问（看到 `You're free as a bird!`），找出浏览器所用 IP 地址，在配置文件 `config.json` 中增加字段，填入该 IP 地址：

```json
{
    "lookup": "<IP address>"
}
```

**Comment by opsforce** [comment]
刚刚试了一下，我换成欧洲的节点就ok了，可能先前用的几个美区的ip被封了
