### ISSUE TITLE
部署在Railway上无法使用

### ISSUE THREAD

**Issue by longke233** [totravel/shadowsocks-ws#4]
Railway部署，请问有详细配置教程吗？

**Comment by totravel** [comment]
要部署到 Railway，只需点击 README 中的 Deploy on Railway 按钮，然后在新的页面上填写加密方法和密码并点击底部的 Deploy 按钮即可。

目前，shadowsocks-ws 支持一键部署到 Heroku 和 Railway，在这两个平台上都能正常工作。当然，shadowsocks-ws 也可以部署到常规的 VPS 上。

如需进一步的帮助，请详细描述你遇到的问题。

**Comment by totravel** [comment]
你提供的服务器都可以正常访问。你的本地配置有误，请按照文档配置。

![图片](https://user-images.githubusercontent.com/22211266/163181164-729eebda-ea63-4abd-bae0-0b2e5984cd9e.png)
