### ISSUE TITLE
clash 是不是不支持shadowsocks-ws？？

### ISSUE THREAD

**Issue by kitkw** [totravel/shadowsocks-ws#5]
v2rayN 下能用。但我常用的openclash连不上.........

**Comment by totravel** [comment]
在本地工作的 shadowsocks-ws 客户端（以下简称 ss-ws-local）相当于一个 Shadowsocks 服务器。理论上，支持 Shadowsocks 协议的客户端（以下简称 ss-local），如 [Shadowsocks for Windows](https://github.com/shadowsocks/shadowsocks-windows)、[Clash for Windows](https://github.com/ender-zhao/Clash-for-Windows_Chinese)、[v2rayN](https://github.com/2dust/v2rayN) 和 [SagerNet for Android](https://github.com/SagerNet/SagerNet)，都可以和 ss-ws-local 搭配使用。当 ss-local 和 ss-ws-local 位于不同的设备时，要在 ss-local 的配置中将服务器的 IP 地址修改为 ss-ws-local 的 IP 地址。

基于 [Clash](https://github.com/Dreamacro/clash) 的客户端有很多，但它们的配置文件的格式都相同（`.yaml` 格式）。对于这类客户端，shadowsocks-ws 提供了 3 个配置文件的模板 `clash.yaml.example`、`blacklist.yaml.example` 和 `whitelist.yaml.example`，并以 [Clash for Windows](https://github.com/ender-zhao/Clash-for-Windows_Chinese) 为例介绍这类客户端的用法。后两个配置文件依赖 [Loyalsoldier/clash-rules](https://github.com/Loyalsoldier/clash-rules) 提供的规则集。规则集可以借助脚本 `ruleset.sh` 下载。

实际的部署环境可能与示例存在较大差异，配置文件和脚本可能需要做相应调整。

**Comment by totravel** [comment]
shadowsocks-ws 与基于 [Clash](https://github.com/Dreamacro/clash) 的客户端搭配使用的方法步骤，请参考 [README - 本地配置 - Clash for Windows](https://github.com/totravel/shadowsocks-ws#clash-for-windows)。如需更多帮助，请提供更多信息。

**Comment by kitkw** [comment]
cipher: aes-256-gcm   password: "secret"  是对的clash还是不行。ShadowSocksR Plus+ 客户端也用不了........   现在只有在V2rayN下正常😣  是不是这些客户端口都不支持shadowsocks的ws协议

**Comment by totravel** [comment]
ss-ws-local 存在的目的就是为了兼容常规的 ss-local。它的作用是将 Shadowsocks 协议的流量包装成 WebSocket 协议的流量再转发给 ss-ws-server。对于 ss-local 来说，ss-ws-local 就是 ss-server。因此，支持 Shadowsocks 协议的客户端理论上都可以和 ss-ws 搭配使用。不同的 ss-local 之间可能存在较大差异，比如 [Clash for Windows](https://github.com/ender-zhao/Clash-for-Windows_Chinese) 不会自动切换到新的配置，具体用法和注意事项请参考相关文档。请认真阅读以上回复和相关文档。
